[project]
org-name= "wso2"
license= ["Apache-2.0"]
authors = ["WSO2"]
version= "1.0.0"
keywords = ["amazonsqs", "Amazon", "SQS", "Ballerina", "connector", "client"]
repository = "https://github.com/wso2-ballerina/module-amazonsqs"